services:
  api:
    build:
      context: .
      target: development
    container_name: retrieve-countries-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/app/src # hot-reload source
      - ./test:/app/test
      - sqlite-data-dev:/app/data
    ports:
      - '${PORT:-3000}:3000'

volumes:
  sqlite-data-dev:
